# Generated by Django 4.0.1 on 2022-02-28 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Footer/')),
            ],
        ),
        migrations.CreateModel(
            name='FooterLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlLink', models.URLField()),
                ('type', models.CharField(max_length=35)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PageInfo.footer')),
            ],
            options={
                'unique_together': {('type', 'urlLink')},
            },
        ),
    ]
