# Generated by Django 4.0.1 on 2022-03-14 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0004_rename_emailverfied_profile_emailverified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lightMode',
        ),
    ]
