# Generated by Django 4.0.4 on 2022-06-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0006_profile_lower_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='publicComment',
            field=models.BooleanField(default=False),
        ),
    ]
