# Generated by Django 4.0.5 on 2022-07-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='customObject',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
