# Generated by Django 4.0.1 on 2022-03-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthGroup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmetadata',
            name='number',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
