# Generated by Django 4.0.1 on 2022-03-23 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AuthGroup', '0003_rename_token_emailmetadata_djangotoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmetadata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
