# Generated by Django 4.0.1 on 2022-02-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayGround', '0002_alter_imagepost_file_alter_imagepost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
