# Generated by Django 4.0.1 on 2022-02-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayGround', '0003_alter_imagepost_file_alter_imagepost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('number', models.ImageField(upload_to='')),
            ],
        ),
    ]
