# Generated by Django 4.0.1 on 2022-02-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlayGround', '0004_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='number',
        ),
    ]
