# Generated by Django 4.0.1 on 2022-02-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayGround', '0005_remove_data_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='number',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
