export enum ActionTypes {
  GET_COMMENT = '[COMMENT] getting COMMENT',
  GET_COMMENT_FAILURE = '[COMMENT] getting COMMENT failed',
  GET_COMMENT_SUCCESS = '[COMMENT] getting COMMENT succeeded',

  POST_COMMENT = '[COMMENT] post COMMENT',
  POST_COMMENT_FAILURE = '[COMMENT] post COMMENT failed',
  POST_COMMENT_SUCCESS = '[COMMENT] post COMMENT succeeded',

  POST_COMMENT_REPLY = '[COMMENT] post reply  COMMENT',
  POST_COMMENT_REPLY_FAILURE = '[COMMENT] post reply COMMENT failed',
  POST_COMMENT_REPLY_SUCCESS = '[COMMENT] post reply COMMENT succeeded',

  DELETE_COMMENT = '[COMMENT] delete COMMENT',
  DELETE_COMMENT_FAILURE = '[COMMENT] delete COMMENT failed',
  DELETE_COMMENT_SUCCESS = '[COMMENT] delete COMMENT succeeded',

  UPDATE_COMMENT = '[COMMENT] update COMMENT',
  UPDATE_COMMENT_FAILURE = '[COMMENT] update COMMENT failed',
  UPDATE_COMMENT_SUCCESS = '[COMMENT] update COMMENT succeeded',
}
